### ISSUE TITLE
Tutorial23 mesh lost

### ISSUE THREAD

**Issue by yangyaoheng** [emeiri/ogldev#12]
Content directory doesn't include Zombie.obj that is used in Tutorial23.cpp  line 149. The same as Tutorial23.cpp line 156.

**Comment by emeiri** [comment]
I will check with the model owner whether I'm allowed to check it into my repo. In the meantime you can get it at https://www.cgtrader.com/free-3d-models/character/fantasy-character/female-zomebie-by-pimmy

**Comment by emeiri** [comment]
Model is checked in to ogldev/Content/Zombie.obj

**Comment by yangyaoheng** [comment]
that's great!!
