### ISSUE TITLE
Bug in `Matrix4f::InitRotationY()`?

### ISSUE THREAD

**Issue by ramiromagno** [emeiri/ogldev#14]
First off, thanks for sharing these amazing tutorials.

Should not the signs of the `sin()` elements be swapped?

Meaning, should it not be:
```
m[0][2] = sinf(y)
```

and 

```
m[2][0] = -sinf(y)
```

instead?

https://github.com/emeiri/ogldev/blob/72b3ddb8e4f20f618f330bd807a81a5e4b1ff5fc/Common/math_3d.cpp#L126-L132

**Comment by emeiri** [comment]
This is a left handed system so this one is actually correct, but it seems that I got it flipped on the X and Z axes. I've just pushed a fix. Please let me know what you think.

Thanks for the feedback!

**Comment by ramiromagno** [comment]
Thank you. I think the three rotations are now coherent among themselves.
