### ISSUE TITLE
tutorial52 vulkan triangle failed

### ISSUE THREAD

**Issue by chairwa** [emeiri/ogldev#15]
./tutorial52
XCB connection opened
XCB screen 0x55b65c1096f4
Window 2800000 created
Found 18 extensions
Instance extension 0 - VK_KHR_device_group_creation
Instance extension 1 - VK_KHR_external_fence_capabilities
Instance extension 2 - VK_KHR_external_memory_capabilities
Instance extension 3 - VK_KHR_external_semaphore_capabilities
Instance extension 4 - VK_KHR_get_physical_device_properties2
Instance extension 5 - VK_KHR_get_surface_capabilities2
Instance extension 6 - VK_KHR_surface
Instance extension 7 - VK_KHR_surface_protected_capabilities
Instance extension 8 - VK_KHR_wayland_surface
Instance extension 9 - VK_KHR_xcb_surface
Instance extension 10 - VK_KHR_xlib_surface
Instance extension 11 - VK_EXT_debug_report
Instance extension 12 - VK_KHR_display
Instance extension 13 - VK_KHR_get_display_properties2
Instance extension 14 - VK_EXT_acquire_xlib_display
Instance extension 15 - VK_EXT_direct_mode_display
Instance extension 16 - VK_EXT_display_surface_counter
Instance extension 17 - VK_EXT_debug_utils
Surface created
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Num physical devices 2
Device name: Intel(R) Xe Graphics (TGL GT2)
    API version: 1.2.182
    Num of family queues: 1
    Format 50 color space 0
    Format 44 color space 0
Image usage transfer src is supported
Image usage transfer dest is supported
Image usage sampled is supported
Image usage color attachment is supported
Number of presentation modes 4
Num memory types 1
0: (f) DEVICE LOCAL HOST VISIBLE HOST COHERENT HOST CACHED 
Num heap types 1
Device name: llvmpipe (LLVM 12.0.0, 256 bits)
    API version: 1.1.182
    Num of family queues: 1
    Format 50 color space 0
    Format 44 color space 0
Image usage transfer src is supported
Image usage transfer dest is supported
Image usage sampled is supported
Image usage color attachment is supported
Number of presentation modes 4
Num memory types 1
0: (f) DEVICE LOCAL HOST VISIBLE HOST COHERENT HOST CACHED 
Num heap types 1
Family 0 Num queues: 1
    GFX Yes, Compute Yes, Transfer Yes, Sparse binding No
Using GFX device 0 and queue family 0
Family 0 Num queues: 1
    GFX Yes, Compute Yes, Transfer Yes, Sparse binding No
Device created
tutorial52: tutorial52.cpp:103: void OgldevVulkanApp::CreateSwapChain(): Assertion `NumImages >= SurfaceCaps.minImageCount' failed.
aborted (core dumped)

**Comment by emeiri** [comment]
It looks like the MESA driver is not able to fully support the Intel GPU. The assertion that fails checks that two images is within the range of minimum and maximum number of images. On my machine I get 2 and 8, respectively. Try to switch to the Intel driver.

**Comment by emeiri** [comment]
Closing the issue due to no update. If the problem persists please reopen. Thanks for reporting!
