### ISSUE TITLE
LNK2019 issue while trying to add to another proj

### ISSUE THREAD

**Issue by xiaossr** [emeiri/ogldev#19]
Hello!

I am trying to use your code from tutorial 31 (on youtube) to select objects in a project I am working on. To do this, I added your header files from the Include folder to mine. I did not add any other code from other folders, just the Include folder and the picking_technique and picking_texture header and cpp files. I also rearranged the assimp folders, deleting assimp5.  However, I'm getting LNK2019 errors from your code in the .obj files. I am using VS2017. I tried running the solutions from your project and it worked fine.

There are no red squiggly lines to tell me I've written something wrong, and I don't think I missed anything from your header files. Is there something I didn't consider here?

Errors are below.. Thanks so much in advance!
![lnk2019error](https://user-images.githubusercontent.com/63619055/207183235-70b0696f-6ad6-41df-ab44-07af5e8b497f.jpg)

**Comment by emeiri-intel** [comment]
You need to add ogldev/Common/technique.cpp. Most of my projects depend on stuff from the Common directory. Also, you need to link with ogldev/Windows/Lib/glew32.lib.

**Comment by xiaossr** [comment]
Thank you! I added both, but there are still LNK2019 errors - now within technique.obj as well. Are there any other files I need to add?

**Comment by xiaossr** [comment]
Since I am on windows, I do not have a build.sh file for my work. However, I saved the output in building. It is attached below:
[buildlog.txt](https://github.com/emeiri/ogldev/files/10219315/buildlog.txt)

**Comment by emeiri-intel** [comment]
I mean in the my directory of my tutorial.
The build log says you need to link with ogldev/Windows/Lib/glew32.lib.

**Comment by emeiri-intel** [comment]
And you also need ogldev/Common/ogldev_util.cpp.

**Comment by xiaossr** [comment]
I added all files that your build log says was included, but I cannot find AntTweakBar64.lib, so my build is failing so far.

**Comment by emeiri-intel** [comment]
I'm not using it anymore. You can remove it.

**Comment by xiaossr** [comment]
Hm, I'm having some issues with Glew32.lib . That might just be on my side though- additionally, should I include all files from the Common folder? Are they mutually dependent on each other?

**Comment by emeiri** [comment]
You don't need to add all the files from the Common directory. Just the functionality that you need. Each tutorial directory has a build.sh file that specifies the required files. You can also look at my Visual Studio solution to see which files are built in each project. What is exactly the problem with glew32.lib? You can clone the sources from https://github.com/nigels-com/glew.git and build it yourself. I have a few more details here: https://youtu.be/WMTxY14aJJE.

**Comment by xiaossr** [comment]
I've figured it out - thank you so much! One more question - if I were to use my own camera system rather than yours, would that be a huge change or no? Is it enough to have the rotation values in the window?

**Comment by emeiri** [comment]
I use a left handed coordinate system. If you use right handed you have to make sure to place the object on the negative Z in order to see them. Other than that I guess your camera system should work.
