### ISSUE TITLE
Can't build tutorial 38

### ISSUE THREAD

**Issue by derkder** [emeiri/ogldev#20]
Hello,
I'm on Windows and here is what I get when I run /tutorial38:

Shading model 3
Loaded ambient color [0.640000 0.640001 0.640000]
Loaded diffuse color [0.640000 0.640000 0.640000]
Loaded specular color [0.000000 0.000000 0.000000]
Invalid shader program: 'Validation Error: Samplers of different types point to the same texture unit
Validation Error: Samplers of different types point to the same texture unit
Validation Error: Samplers of different types point to the same texture unit
'
!!! Debug callback !!!
Debug message: id 2, API_ID_RECOMPILE_FRAGMENT_SHADER performance warning has been generated. Fragment shader recompiled due to state change.
Message source: API
Error type: Performance
Severity: Medium

Sorry if it is beacause my wrong operatiion, I`m just new to the whole openGL

**Comment by emeiri** [comment]
I fixed the shadow bug.

**Comment by derkder** [comment]
Thank you！！！It works, I can see the house now.
