### ISSUE TITLE
I had two errors building the files on windows

### ISSUE THREAD

**Issue by VitorMagno** [emeiri/ogldev#22]
![image](https://user-images.githubusercontent.com/45520686/234843723-c2cecd4e-c543-47a8-a9f4-90f81f91bc2f.png)

**Comment by emeiri** [comment]
Did you change something in Tutorial24? It doesn't include math_3d.cpp. Only assimp_sandbox.cpp.

**Comment by VitorMagno** [comment]
no, i just clicked to build the solutions

**Comment by emeiri** [comment]
OK, this is a bit strange. Please check that the 'Source Files' folder under Tutorial24 contains only assimp_sandbox.cpp (I'm referring to Visual Studio, not the directory). Right click Tutorial24 and 'Rebuild' and let's see what happens.

**Comment by VitorMagno** [comment]
I don't know what happened but I just rebuild everything and this time it completed without errors. Thank you

**Comment by emeiri** [comment]
You're welcome!
