### ISSUE TITLE
nullptr exception while running OpenGL tutorial #28

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [emeiri/ogldev#29]
Maybe you have some idea what I am doing wrong. Seems like something with my VS project setup?

![image](https://github.com/emeiri/ogldev/assets/6131040/ad62d144-280a-4213-b021-ba03a3f3e6bb)

**Comment by dmitrykolesnikovich** [comment]
What is confusing is that `paiMesh->mNumFaces == 628` but `paiMesh->mFaces == NULL`

![image](https://github.com/emeiri/ogldev/assets/6131040/977ceebd-ce3b-4b78-905f-4d931bfbb49c)

**Comment by dmitrykolesnikovich** [comment]
BTW earlier I commented out `include "assimp/contrib/utf8cpp/source/utf8.h"` because it was not able to found this `utf8.h`
 file

![image](https://github.com/emeiri/ogldev/assets/6131040/cade0af0-cadb-4082-8211-c686856de7d6)

**Comment by emeiri** [comment]
Sorry about that. Looks like a bad assimp update. I checked in a fix. Please pull and try again.

**Comment by dmitrykolesnikovich** [comment]
![image](https://github.com/emeiri/ogldev/assets/6131040/279aec3b-ea8b-4e98-affc-d36ede28abf8)

**Comment by emeiri** [comment]
Oops. The dll is now checked in as well.

**Comment by dmitrykolesnikovich** [comment]
It's working now, although there is strange behaviour, when I'm clicking `D` key all the scene is dissapearing. Arrow keys are working.

**Comment by dmitrykolesnikovich** [comment]
Not found: `3rdparty/meshoptimizer/src/meshoptimizer.h`

**Comment by emeiri** [comment]
This one is trickier. I may have created the submodule incorrecty.
Try the following:
git submodule init
git pull --recurse-submodules

**Comment by dmitrykolesnikovich** [comment]
![image](https://github.com/emeiri/ogldev/assets/6131040/3027004e-7a0b-48fb-b279-3f34cbee7eb8)

**Comment by emeiri** [comment]
This one actually works ok for me. Can you please show the callstack?

**Comment by dmitrykolesnikovich** [comment]
![image](https://github.com/emeiri/ogldev/assets/6131040/7e205e52-769c-478d-9c42-17ae00717b7f)

**Comment by emeiri** [comment]
I see that this error is in tutorial 40 which is also working ok for me. 
Are 28/29 working ok?
Please make sure that the project is linked with assimp-vc143-mt.lib and not 142. This sure looks like the same incompatibility as before.
You can also place a breakpoint in BasicMesh::GetMaterial and inspect the things that it accesses.

**Comment by emeiri** [comment]
Closing this issue as there hasn't been an update. Please reopen if needed.
