### ISSUE TITLE
Terrain13

### ISSUE THREAD

**Issue by qgxx** [emeiri/ogldev#31]
When using vs2022 to run the Terrain13 project, the file 3rdparty/meshoptimizer/src/meshoptimizer.h cannot be found.

**Comment by emeiri** [comment]
Looks like the meshoptimizer submodule was not updated. You can either clone the repo again and enable 'clone recursively' (or add '--recurse-submodules' on the command line) or run the following in the existing repo:

git submodule init
git submodule update
