### ISSUE TITLE
Vulkan tutorial: Missing debug type in initiation

### ISSUE THREAD

**Issue by ebarland** [emeiri/ogldev#32]
GetDebugType switches on VK_DEBUG_UTILS_MESSAGE_TYPE_DEVICE_ADDRESS_BINDING_BIT_EXT, but this is never set in VulkanCore::CreateInstance or VulkanCore::CreateDebugCallback.

**Comment by emeiri** [comment]
GetDebugType is generic in the sense that it handles all the message type. It doesn't care which specific types you enabled. I enabled three out of four that I thought are the most important but feel free to enable address binding as well.
