### ISSUE TITLE
Small corrections around vkDestroySurfaceKHR

### ISSUE THREAD

**Issue by ookami125** [emeiri/ogldev#35]
I'm going through the series as a refresher for myself and I noticed some minor issues in the code.
[core.cpp#L74](https://github.com/emeiri/ogldev/blob/master/Vulkan/VulkanCore/Source/core.cpp#L74) vkDestroySurfaceKHR is called, but the function pulled is store in vkDestroySurface (without the KHR). I think either changing the function to vkDestroySurface or removing the code to get the function can be removed. I've tested both and they both work, but I'm running on linux and I'm not sure if everything works perfectly the same on windows.

And more of a nitpick the OGLDEV_ERROR above reports that "vkDestroyDebugUtilsMessenger" address can't be found, I think that should be changed to "vkDestroySurfaceKHR" to reflect what's actually being grabbed. Assuming that the code is actually kept, changing it will avoid potential confusion while debugging.

**Comment by emeiri** [comment]
Fixed.
Thanks for the feedback!
