### ISSUE TITLE
Vulkan Tutorial 1 will not render on Wayland

### ISSUE THREAD

**Issue by alexk101** [emeiri/ogldev#36]
Not something I am sure you are aware of, given that your development environment is Windows, but the first Vulkan tutorial will not render a window on systems running Wayland. This is due to the fact that 

"This is by design. A Wayland window is not shown until a buffer is commited."

_Originally posted by @Jjagg in https://github.com/glfw/glfw/issues/1398#issuecomment-450572785_

Perhaps make a note of this somewhere.

**Comment by emeiri** [comment]
Thanks! I've added a note about it.
