### ISSUE TITLE
tutorial 38 has segmentation default 

### ISSUE THREAD

**Issue by killerdevildog11** [emeiri/ogldev#6]
when building with the included scripts and the bin is ran it auto closes

**Comment by Angular-Angel** [comment]
try running it with gdb, and post the output! Also, see my issue for tutorial 36, you're probably having many of the same issues.

**Comment by emeiri** [comment]
I've just pushed a few fixes. Can you please recheck?

**Comment by emeiri** [comment]
I'm closing this issue for now. Please reopen if there is still a problem. Thanks for the report.
