### ISSUE TITLE
ogldev_texture.cpp uses GL_CLAMP_TO_EDGE when it shouldn't.

### ISSUE THREAD

**Issue by Angular-Angel** [emeiri/ogldev#7]
In lines 72 and 73, this file sets texture wrap to clamp to edge, which makes the textures draw incorrectly for Tutorial 36, and probably for other tutorials as well. Simply commenting out those two lines fixes the problem for tutorial 36.

**Comment by emeiri** [comment]
I replaced GL_CLAMP_TO_EDGE with GL_REPEAT which is the default value but if we don't set the wrap mode it triggers a GL_ERROR (only on Windows, for some reason).

Thanks for the feedback! I'll close this bug. Please let me know if the solution doesn't work.
